/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/navigation/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/navigation/AppFooter.vue')['default']
    AppTopbar: typeof import('./src/components/navigation/AppTopbar.vue')['default']
    Babylon: typeof import('./src/components/babylon/Babylon.vue')['default']
    BabylonViewer: typeof import('./src/components/babylon/BabylonViewer.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    GraphicsSettings: typeof import('./src/components/babylon/GraphicsSettings.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MaterialsPanel: typeof import('./src/components/babylon/MaterialsPanel.vue')['default']
    ModelingToolbar: typeof import('./src/components/babylon/ModelingToolbar.vue')['default']
    ProductOverviewWidget: typeof import('./src/components/dashboard/ProductOverviewWidget.vue')['default']
    RecentActivityWidget: typeof import('./src/components/dashboard/RecentActivityWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendWidget: typeof import('./src/components/dashboard/SalesTrendWidget.vue')['default']
    SceneManagementToolbar: typeof import('./src/components/babylon/SceneManagementToolbar.vue')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    ViewToolbar: typeof import('./src/components/babylon/ViewToolbar.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
